### ISSUE TITLE
Невозможно зайти в админку (config rows) без добавления библиотеки "import_export" в INSTALLED_APPS

### ISSUE THREAD

**Issue by samoilovartem** [factory5group/django-liveconfigs#2]
Всем привет) 

Спасибо за интересный доклад и за данную либу. 

Сейчас рассматриваю ее для одного из своих проектов, но сходу столкнулся с багом - невозможно зайти в админку (config rows) без добавления библиотеки `import_export` в INSTALLED_APPS, а об этом в документации нет ни слова. Возможно вы никогда еще не ставили `django-liveconfigs` в проект, в котором не используется `django-import-export`, поэтому не смогли это поймать)

Вот такая ошибка выходит:

<img width="1317" alt="image" src="https://github.com/factory5group/django-liveconfigs/assets/98294957/36e3a10c-98a8-4131-88fa-3a9981e25590">

Как видно, просто не хватает шаблона из `django-import-export`. 

Пожалуйста, отразите этот момент в документации, чтобы другие разработчики с этим не столкнулись. 

P.S. Также, было бы здорово указать как именно устанавливать вашу библиотеку:  `poetry add django-liveconfigs` или `pip install django-liveconfigs` и т.д. Повезло что название совпадает с pypi, но это далеко не всегда так. 
Кроме того нет ни слова про необходимость применения миграций, а без них ничего не заработает) 

В целом, пока я писал это все - осознал, что могу и сам законтребьютить. Пожалуйста, дайте знать, если хотите чтобы я это сделал.

**Comment by eugene-katsevman** [comment]
Привет!
Будем рады пулл-реквестам, ну и на этой неделе я сам поправлю часть.
Спасибо за обратную связь, очень круто, что библиотека оказалась полезна.
